handlebars ./src/components/Header/Header.hbs -f ./src/components/Header/Header.precompiled.js
handlebars ./src/components/MoviePoster/MoviePoster.hbs -f ./src/components/MoviePoster/MoviePoster.precompiled.js
handlebars ./src/components/PosterCarousel/PosterCarousel.hbs -f ./src/components/PosterCarousel/PosterCarousel.precompiled.js
handlebars ./src/components/MoviePlayer/MoviePlayer.hbs -f ./src/components/MoviePlayer/MoviePlayer.precompiled.js
handlebars ./src/components/Pagination/Pagination.hbs -f ./src/components/Pagination/Pagination.precompiled.js
handlebars ./src/components/SupportTicketsHero/SupportTicketsHero.hbs -f ./src/components/SupportTicketsHero/SupportTicketsHero.precompiled.js
handlebars ./src/components/SupportTicketsSidebar/SupportTicketsSidebar.hbs -f ./src/components/SupportTicketsSidebar/SupportTicketsSidebar.precompiled.js
handlebars ./src/components/SupportTicketsConversation/SupportTicketsConversation.hbs -f ./src/components/SupportTicketsConversation/SupportTicketsConversation.precompiled.js
handlebars ./src/components/WatchPartyRoomChat/WatchPartyRoomChat.hbs -f ./src/components/WatchPartyRoomChat/WatchPartyRoomChat.precompiled.js
handlebars ./src/pages/Main/Main.hbs -f ./src/pages/Main/Main.precompiled.js
handlebars ./src/pages/Movie/Movie.hbs -f ./src/pages/Movie/Movie.precompiled.js
handlebars ./src/pages/SignIn/SignIn.hbs -f ./src/pages/SignIn/SignIn.precompiled.js
handlebars ./src/pages/SignUp/SignUp.hbs -f ./src/pages/SignUp/SignUp.precompiled.js
handlebars ./src/pages/Profile/Profile.hbs -f ./src/pages/Profile/Profile.precompiled.js
handlebars ./src/pages/Settings/Settings.hbs -f ./src/pages/Settings/Settings.precompiled.js
handlebars ./src/pages/Actor/Actor.hbs -f ./src/pages/Actor/Actor.precompiled.js
handlebars ./src/pages/Catalog/Catalog.hbs -f ./src/pages/Catalog/Catalog.precompiled.js
handlebars ./src/pages/WatchParty/WatchParty.hbs -f ./src/pages/WatchParty/WatchParty.precompiled.js
handlebars ./src/pages/SupportTickets/SupportTickets.hbs -f ./src/pages/SupportTickets/SupportTickets.precompiled.js
handlebars ./src/pages/SupportCreate/SupportCreate.hbs -f ./src/pages/SupportCreate/SupportCreate.precompiled.js
handlebars ./src/pages/Friends/Friends.hbs -f ./src/pages/Friends/Friends.precompiled.js
handlebars ./src/pages/NotFound/NotFound.hbs -f ./src/pages/NotFound/NotFound.precompiled.js
